name: moodexample
description: 管理自己的情绪，记录当下所见所想。
publish_to: 'none'
version: 1.9.11+491

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: 0.20.2
  path: 1.9.1
  path_provider: 2.1.5
  provider: 6.1.5+1
  sqflite: 2.4.2
  shared_preferences: 2.5.3
  go_router: 17.0.0
  flutter_zoom_drawer: 3.2.0
  flutter_smart_dialog: 4.9.8+9
  table_calendar: 3.2.0
  flutter_slidable: 4.0.3
  card_swiper: 3.0.1
  fl_chart: 1.1.1
  excel: 4.0.6
  share_plus: 12.0.1
  file_picker: 10.3.6
  webview_flutter: 4.13.0
  ditredi: 2.0.2
  vector_math: 2.2.0
  awesome_notifications: 0.10.1
  bonfire: 3.16.1
  flame: 1.32.0
  flutter_screen_lock: 9.2.2+2
  local_auth: 3.0.0
  local_auth_android: 2.0.0
  local_auth_darwin: 2.0.0
  flutter_tilt: 3.3.2
  remixicon: 1.4.1

dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: any

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/onboarding/
    - assets/images/woolly/
    - assets/3d/city/
    - assets/images/game/mini_fantasy/
    - assets/images/game/mini_fantasy/tiles/
    - assets/images/game/mini_game/
    - assets/images/game/mini_game/tiles/
    - assets/images/game/mini_game/enemy/orc/
    - assets/images/game/mini_game/enemy/boss/
    - assets/images/game/mini_game/player/human/
